bmi-nwm:
  archive: harvey
  comid: [5781915]
  config: short_range
  end_date: '2017-09-06'
  geom: channel_rt
  init_time: 0
  output: ''
  start_date: '2017-08-23'
  time_lag: 0
  variable: streamflow
